# default configuration
baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Home"

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
URL = "https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js"


# menu
[[menu.main]]
URL = ""
name = "Home"
weight = 1

[[menu.main]]
URL = "about"
name = "About"
weight = 2

[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4


# default parameters
[params]
home = "Home"
logo = "images/logo.svg"
# theme color
theme_color = "#00A1E9"
# contact info
twitter = "m_dotcube"
email = "dotcubecrafter@gmail.com"
address = "University of Miyazaki"
address_link = "http://www.miyazaki-u.ac.jp/"
# meta description
noindex = false  # true にすると、検索エンジンに登録されなくなる。プレビュー用ページを公開するときなどに ture にする。
author = "dot cube"
description = "\"dot cube\"は宮崎大学のデジタルコンテンツ制作サークルです。ゲーム制作や競技プログラミング、ハッカソンへの参加と行った活動を主に行っています。"
# google analitycs
use_google_analitycs = false  # Google Analitycs を使用するか否か。プレビュー用ページなどのページをビルドする際は false にする。
google_analitycs_id = "UA-163090822-1" # Your ID
# copyright
copyright = "Copyrighht &copy; 2020 [dot cube](https://dot-cube.github.io)"


# contact
[params.contact]
title = "Contact"
subtitle = "連　絡"
description = "入部希望や御用のある方は以下のフォーム又は、ページ下部の連絡先より連絡していただけると幸いです。"
form_title = "連絡フォーム"
send_button_description = "Powered by Google Forms"

# Google フォームを組み込む方法: https://qiita.com/curioussafuta/items/fa077cbf820faca30598
form_action = "https://docs.google.com/forms/u/1/d/e/1FAIpQLSchSYZuXzp2w4_PkNVPYkYBiTAxOqGfpM2wMHADKNAona8g8Q/formResponse" # contact form works with : Google Forms
name_area_name = "entry.624016201"
email_area_name = "entry.1770681918"
message_area_name = "entry.1806422541"

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# social site
[[params.social]]
URL = "https://twitter.com/m_dotcube"
icon = "ti-twitter-alt"

[[params.social]]
URL = "https://github.com/dot-cube"
icon = "ti-github"

[[params.social]]
URL = "mailto:dotcubecrafter@gmail.com"
icon = "ti-email"

# [[params.social]]
# URL = "#"
# icon = "ti-dribbble"
